name: Deploy to EC2 (Test)

on:
  push:
    branches:
      - test

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: 📦 Install dependencies
        working-directory: backend
        run: npm install

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /var/www/talentconnect-careercraft
            git pull origin test
            sudo nginx -t
            sudo systemctl reload nginx
            cd backend
            npm install
            pm2 restart talentconnect-api || pm2 start server.js --name talentconnect-api
